ÇOKLU DOĞRUSAL REGRESYON

In [7]:
import pandas as pd
df = pd.read_csv("Advertising.csv")
df = df.iloc[:,1:len(df)]
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [8]:
X = df.drop('sales', axis=1)
y = df[["sales"]]

In [6]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [4]:
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [7]:
#Statsmodels ile model kurmak

In [9]:
!pip install statsmodels

     ---------------------------------------- 0.0/9.2 MB ? eta -:--:--
     ---------------------------------------- 0.0/9.2 MB ? eta -:--:--
     ---------------------------------------- 0.0/9.2 MB 435.7 kB/s eta 0:00:22
     ---------------------------------------- 0.0/9.2 MB 326.8 kB/s eta 0:00:28
     ---------------------------------------- 0.1/9.2 MB 585.1 kB/s eta 0:00:16
      --------------------------------------- 0.1/9.2 MB 774.0 kB/s eta 0:00:12
      --------------------------------------- 0.2/9.2 MB 981.9 kB/s eta 0:00:10
     - -------------------------------------- 0.3/9.2 MB 1.1 MB/s eta 0:00:08
     - -------------------------------------- 0.4/9.2 MB 1.2 MB/s eta 0:00:08
     - -------------------------------------- 0.4/9.2 MB 1.2 MB/s eta 0:00:08
     -- ------------------------------------- 0.6/9.2 MB 1.5 MB/s eta 0:00:06
     --- ------------------------------------ 0.8/9.2 MB 1.8 MB/s eta 0:00:05
     ---- ----------------------------------- 1.0/9.2 MB 2.1 MB/s et

In [12]:
import statsmodels.api as sm

In [13]:
lm = sm.OLS(y, X)

In [14]:
model = lm.fit()

In [15]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  sales   R-squared (uncentered):                   0.982
Model:                            OLS   Adj. R-squared (uncentered):              0.982
Method:                 Least Squares   F-statistic:                              3566.
Date:                Sat, 09 Dec 2023   Prob (F-statistic):                   2.43e-171
Time:                        21:33:34   Log-Likelihood:                         -423.54
No. Observations:                 200   AIC:                                      853.1
Df Residuals:                     197   BIC:                                      863.0
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0538      0.001     40.507      0.000       0.051       0.056
radio          0.2222      0.009     23.595      0.000       0.204       0.241
newspaper      0.0168      0.007      2.517      0.013       0.004       0.030
==============================================================================
Omnibus:                        5.982   Durbin-Watson:                   2.038
Prob(Omnibus):                  0.050   Jarque-Bera (JB):                7.039
Skew:                          -0.232   Prob(JB):                       0.0296
Kurtosis:                       3.794   Cond. No.                         12.6
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [3]:
#scikit learn ile model kurmak

In [4]:
from sklearn.linear_model import LinearRegression
lm = LinearRegression()

In [9]:
model = lm.fit(X, y)

In [10]:
model.intercept_

array([2.93888937])

In [11]:
model.coef_

array([[ 0.04576465,  0.18853002, -0.00103749]])

Tahmin

Sales = 2.94 + TV*0.04 + radio*0.19 - newspaper*0.001

In [20]:
2.94 + 30*0.04 + 10*0.19 - 40*0.001

5.999999999999999

In [21]:
yeni_veri = [[30],[10],[40]]

In [23]:
import pandas as pd
yeni_veri = pd.DataFrame(yeni_veri).T

In [24]:
yeni_veri

0   1   2
0  30  10  40

In [25]:
model.predict(yeni_veri)

C:\Users\senav\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[6.15562918]])

In [26]:
from sklearn.metrics import mean_squared_error

In [28]:
MSE =mean_squared_error(y, model.predict(X))
MSE

2.784126314510936

In [29]:
import numpy as np
RMSE = np.sqrt(MSE)
RMSE

1.6685701407225697

MODEL TUNİNG (MODEL DOĞRULAMA)

In [30]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [31]:
#sinama seti
from sklearn.model_selection import train_test_split

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.20, random_state= 99)

In [34]:
X_train.head()

TV  radio  newspaper
16    67.8   36.6      114.0
51   100.4    9.6        3.6
97   184.9   21.0       22.0
164  117.2   14.7        5.4
71   109.8   14.3       31.7

In [36]:
y_train.head()

sales
16    12.5
51    10.7
97    15.5
164   11.9
71    12.4

In [37]:
X_test.head()

TV  radio  newspaper
135  48.3   47.0        8.5
127  80.2    0.0        9.2
191  75.5   10.8        6.0
66   31.5   24.6        2.2
119  19.4   16.0       22.3

In [38]:
y_test.head()

sales
135   11.6
127    8.8
191    9.9
66     9.5
119    6.6

In [40]:
lm = LinearRegression()
model = lm.fit(X_train, y_train)

In [41]:
#eğitim hatası
np.sqrt(mean_squared_error(y_train, model.predict(X_train)))

1.7236824822650751

In [42]:
#test hatası
np.sqrt(mean_squared_error(y_test, model.predict(X_test)))

1.4312783138301637

In [43]:
#k-katlı cv
from sklearn.model_selection import cross_val_score

In [44]:
cross_val_score(model, X_train, y_train, cv=10, scoring= "neg_mean_squared_error")

array([-2.1019073 , -2.48953197, -3.09704214, -2.34694216, -3.68175761,
       -1.8691401 , -3.18173007, -4.1927349 , -2.17128376, -8.03821974])

In [47]:
np.mean(-cross_val_score(model, X_train, y_train, cv=10, scoring= "neg_mean_squared_error"))

3.3170289742341255

In [45]:
#cv rmse
np.sqrt(np.mean(-cross_val_score(model, X_train, y_train, cv=10, scoring= "neg_mean_squared_error")))

1.8212712522395245

In [48]:
#cv rmse
np.sqrt(np.mean(-cross_val_score(model, X, y, cv=10, scoring= "neg_mean_squared_error")))

1.7492763126843383